apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-teamcity-agent-37a8958e
  namespace: teamcity
  labels:
    type: teamcity-agent-cache
spec:
  capacity:
    storage: 128Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/boom2/cache-teamcity-agent-37a8958e
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k88936-sa5212m4
