---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rustfs-config
  namespace: rustfs
data:
  RUSTFS_CONSOLE_ENABLE: "true"
  RUSTFS_VOLUMES: /data
  # RUSTFS_VOLUMES: http://rustfs-{0...1}.rustfs-headless.rustfs.svc.cluster.local:9000/data
  # RUSTFS_SERVER_DOMAINS: rustfs.k88936.top,rustfs-0.rustfs-headless.rustfs.svc.cluster.local:9000,rustfs-1.rustfs-headless.rustfs.svc.cluster.local:9000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rustfs
  namespace: rustfs
spec:
  podManagementPolicy: Parallel
  replicas: 1
  serviceName: rustfs-headless
  selector:
    matchLabels:
      app: rustfs
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      terminationGracePeriodSeconds: 120
      # topologySpreadConstraints:
      # - maxSkew: 1
      #   topologyKey: kubernetes.io/hostname
      #   whenUnsatisfiable: DoNotSchedule
      #   labelSelector:
      #     matchLabels:
      #       app: rustfs
      # affinity:
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       podAffinityTerm:
      #         topologyKey: kubernetes.io/hostname
      #         labelSelector:
      #           matchLabels:
      #             app: rustfs
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: rustfs
        image: rustfs/rustfs:latest
        command:
        - /bin/sh
        - -c
        - exec /usr/bin/rustfs ${RUSTFS_VOLUMES}
        env:
        - name: RUSTFS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-credentials
              key: accessKey
        - name: RUSTFS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-credentials
              key: secretKey
        envFrom:
        - configMapRef:
            name: rustfs-config
        ports:
        - containerPort: 9000
          name: api
        livenessProbe:
          httpGet:
            path: /health
            port: api
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: api
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: rustfs-logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: longhorn-oss
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 256Gi

---
apiVersion: v1
kind: Service
metadata:
  name: rustfs-headless
  namespace: rustfs
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: rustfs
  ports:
  - name: s3
    port: 80
    targetPort: api

---
apiVersion: v1
kind: Service
metadata:
  name: rustfs
  namespace: rustfs
spec:
  selector:
    app: rustfs
  ports:
  - name: s3
    port: 80
    targetPort: api
  type: ClusterIP