---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rustfs-config
  namespace: rustfs
data:
  RUSTFS_ADDRESS: ":9000"
  RUSTFS_CONSOLE_ENABLE: "true"
  RUST_LOG: "error"
  RUSTFS_OBS_LOG_DIRECTORY: "/var/logs/rustfs/"
---
apiVersion: v1
kind: Service
metadata:
  name: rustfs-headless
  namespace: rustfs
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: rustfs
  ports:
  - name: api
    port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: rustfs
  namespace: rustfs
spec:
  selector:
    app: rustfs
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rustfs
  namespace: rustfs
spec:
  podManagementPolicy: Parallel
  replicas: 2
  serviceName: rustfs-headless
  selector:
    matchLabels:
      app: rustfs
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      terminationGracePeriodSeconds: 120
      # topologySpreadConstraints:
      # - maxSkew: 1
      #   topologyKey: kubernetes.io/hostname
      #   whenUnsatisfiable: DoNotSchedule
      #   labelSelector:
      #     matchLabels:
      #       app: rustfs
      # affinity:
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       podAffinityTerm:
      #         topologyKey: kubernetes.io/hostname
      #         labelSelector:
      #           matchLabels:
      #             app: rustfs
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: rustfs
        image: rustfs/rustfs:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - exec /usr/bin/rustfs ${RUSTFS_VOLUMES}
        env:
        - name: RUSTFS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-credentials
              key: accessKey
        - name: RUSTFS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-credentials
              key: secretKey
        - name: RUSTFS_VOLUMES
          value: http://rustfs-{0...1}.rustfs-headless.rustfs.svc.cluster.local:9000/data
        envFrom:
        - configMapRef:
            name: rustfs-config
        ports:
        - containerPort: 9000
          name: api
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "2"
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 2Gi
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: rustfs-logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: openebs-hostpath
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1024Gi
