---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rustfs-config
  namespace: rustfs
data:
  RUSTFS_CONSOLE_ENABLE: "true"
  RUSTFS_VOLUMES: http://rustfs-{0...3}.rustfs-headless.rustfs.svc.cluster.local:9000/data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rustfs
  namespace: rustfs
spec:
  podManagementPolicy: Parallel
  replicas: 4
  serviceName: rustfs-headless
  selector:
    matchLabels:
      app: rustfs
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      terminationGracePeriodSeconds: 120
      # topologySpreadConstraints:
      # - maxSkew: 1
      #   topologyKey: kubernetes.io/hostname
      #   whenUnsatisfiable: DoNotSchedule
      #   labelSelector:
      #     matchLabels:
      #       app: rustfs
      # affinity:
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       podAffinityTerm:
      #         topologyKey: kubernetes.io/hostname
      #         labelSelector:
      #           matchLabels:
      #             app: rustfs
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: rustfs
        image: rustfs/rustfs:1.0.0-alpha.85
        command:
        - /bin/sh
        - -c
        - exec /usr/bin/rustfs ${RUSTFS_VOLUMES}
        env:
        - name: RUSTFS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-credentials
              key: accessKey
        - name: RUSTFS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-credentials
              key: secretKey
        envFrom:
        - configMapRef:
            name: rustfs-config
        ports:
        - containerPort: 9000
          name: container-port
        livenessProbe:
          httpGet:
            path: /health
            port: container-port
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: container-port
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: local-path
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 64Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rustfs
  namespace: rustfs
spec:
  selector:
    app: rustfs
  ports:
  - name: api
    port: 80
    targetPort: container-port
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: rustfs-headless
  namespace: rustfs
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: rustfs