apiVersion: batch/v1
kind: Job
metadata:
  name: volume-migration
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      name: volume-migration
      labels:
        name: volume-migration
    spec:
      restartPolicy: Never
      containers:
        - name: volume-migration
          image: alpine:3.19
          tty: true
          command: [ "/bin/sh" ]
          args: [ "-c", "apk add --no-cache rsync && rsync -av --delete --progress /mnt/src/ /mnt/dst/" ]
          volumeMounts:
            - name: src
              mountPath: /mnt/src
            - name: dst
              mountPath: /mnt/dst
      volumes:
        - name: src
          persistentVolumeClaim:
            claimName:  data-rustfs-0
          # hostPath:
          #   path: /mnt/tmp
        - name: dst
          persistentVolumeClaim:
            claimName:  data-rustfs-1