apiVersion: batch/v1
kind: Job
metadata:
  namespace: teamcity  # namespace where the pvc's exist
  name: volume-migration
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      name: volume-migration
      labels:
        name: volume-migration
    spec:
      restartPolicy: Never
      containers:
        - name: volume-migration
          image: alpine:3.19
          tty: true
          command: [ "/bin/sh" ]
          # Install rsync then run the copy
          args: [ "-c", "apk add --no-cache rsync && rsync -av --delete --progress /mnt/old/ /mnt/new" ]
          volumeMounts:
            - name: old-vol
              mountPath: /mnt/old
            - name: new-vol
              mountPath: /mnt/new
      volumes:
        - name: old-vol
          hostPath:
            path: /mnt/tmp
        - name: new-vol
          persistentVolumeClaim:
            claimName:  data-teamcity-0 # change to data target pvc