---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: teamcity
  namespace: teamcity
spec:
  serviceName: teamcity
  replicas: 1
  selector:
    matchLabels:
      app: teamcity
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: longhorn
  template:
    metadata:
      labels:
        app: teamcity
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: wait-for-db
          image: busybox:1.37.0
          command:
            - sh
            - -c
            - until nc -z teamcity-postgres 5432; do echo "waiting for postgres"; sleep 3; done
      containers:
        - name: teamcity-server
          image: jetbrains/teamcity-server:latest
          ports:
            - containerPort: 8111
              name: http
          envFrom:
            - secretRef:
                name: teamcity-db-secret
          env:
            - name: TEAMCITY_SERVER_MEM_OPTS
              value: "-Xms512m -Xmx2g"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
            - name: data
              mountPath: /data/teamcity_server/datadir
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 80
          readinessProbe:
            httpGet:
              path: /healthCheck/healthy
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /healthCheck/healthy
              port: http
            initialDelaySeconds: 420
            periodSeconds: 30
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: teamcity
  namespace: teamcity
spec:
  selector:
    app: teamcity
  ports:
    - name: http
      port: 8111
      targetPort: http
  type: ClusterIP