---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  serviceName: nextcloud
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:apache
          imagePullPolicy: IfNotPresent
          ports:
            - name: container-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: nextcloud-config
            - secretRef:
                name: nextcloud-s3-secret
            - secretRef:
                name: nextcloud-db-secret
          env:
            - name: OVERWRITEHOST
              value: nextcloud.k88936.top
            - name: OVERWRITEPROTOCOL
              value: https
          volumeMounts:
            - name: data
              mountPath: /var/www/html
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 32Gi

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  ports:
    - name: service-port
      port: 80
      targetPort: container-port
  selector:
    app: nextcloud