apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: youtrack
  namespace: youtrack
  labels:
    app: youtrack
spec:
  serviceName: youtrack
  replicas: 1
  selector:
    matchLabels:
      app: youtrack
  template:
    metadata:
      labels:
        app: youtrack
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      terminationGracePeriodSeconds: 60
      containers:
      - name: youtrack
        image: jetbrains/youtrack:2025.3.117635
        imagePullPolicy: IfNotPresent
        env:
        - name: YOUTRACK_BASE_URL
          value: https://youtrack.k88936.top
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /opt/youtrack/data
        - name: conf
          mountPath: /opt/youtrack/conf
        - name: logs
          mountPath: /opt/youtrack/logs
        - name: backups
          mountPath: /opt/youtrack/backups
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: longhorn
      resources:
        requests:
          storage: 20Gi
  - metadata:
      name: conf
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: longhorn
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: logs
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: longhorn
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: backups
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: longhorn
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: youtrack
  namespace: youtrack
  labels:
    app: youtrack
spec:
  type: ClusterIP
  selector:
    app: youtrack
  ports:
  - name: http
    port: 80
    targetPort: http