apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudreve-config
  namespace: cloudreve
data:
  conf.ini: |
    [System]
    Mode = master
    Listen = :5212
    SessionSecret = change_this_to_random_string
    HashIDSalt = change_this_to_random_string
