apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudreve-db
  namespace: cloudreve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudreve-avatar
  namespace: cloudreve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
