---
apiVersion: v1
kind: Secret
metadata:
  name: aria2-secret
  namespace: cloudreve
stringData:
  RPC_SECRET: your_aria_rpc_token
  RPC_PORT: "6800"

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudreve-secret
  namespace: cloudreve
stringData:
  ARIA2_HOST: aria2:6800
  ARIA2_SECRET: your_aria_rpc_token
