---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloudreve
  namespace: cloudreve
spec:
  serviceName: cloudreve
  replicas: 1
  selector:
    matchLabels:
      app: cloudreve
  template:
    metadata:
      labels:
        app: cloudreve
    spec:
      containers:
        - name: cloudreve
          image: cloudreve/cloudreve:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: container-port
              containerPort: 5212
          volumeMounts:
            - name: data
              mountPath: /cloudreve/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 64Gi
        storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: cloudreve
  namespace: cloudreve
  labels:
    app: cloudreve
spec:
  ports:
    - name: service-port
      port: 80
      targetPort: container-port
  selector:
    app: cloudreve