apiVersion: v1
kind: PersistentVolume
metadata:
  name: rustfs-data-a4090013
  namespace: rustfs
  labels:
    type: rustfs-data
spec:
  capacity:
    storage: 512Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/storage1/rustfs-data-a4090013
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k88936-sa5212m4
