apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: admin@k88936.top
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        webhook:
         groupName: acme.k88936.top
         solverName: alidns
         config:
          region: ""
          accessKeyIdRef:
            name: alidns-secret
            key: access-key-id
          accessKeySecretRef:
            name: alidns-secret
            key: access-key-secret